name: Azure DevOps CI

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Azure DevOps
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        git remote add azure https://<Azure-DevOps-Repo-URL>
        git push azure main
