name: Azure DevOps CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Azure DevOps
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        git init
        git add .
        git commit -m "commit message"
        git remote add azure https://${{ secrets.AZURE_DEVOPS_TOKEN }}@tfs.astra.co.id/tfs/EnterpriseCollaboration/AstraWebsite/_git/AstraWebsite
        git push azure main
