name: Azure DevOps CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Git user identity
      run: |
        git config --global user.email "adindafebrn@gmail.com"
        git config --global user.name "Adinda F"

    - name: Push to Azure DevOps
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        # Add changes
        git add .
        
        # Check if there are changes to commit
        git diff-index --quiet HEAD || git commit -m "Your commit message"
        
        # Add Azure DevOps remote
        git remote add azure https://${{ secrets.AZURE_DEVOPS_TOKEN }}@tfs.astra.co.id/tfs/EnterpriseCollaboration/AstraWebsite/_git/AstraWebsite
        
        # Push to Azure DevOps
        git push azure main || echo "Nothing to push"
